
###*** App to administer survey. Survey collects respondent data, submits to google sheet. Features:
###* 1. Progress bar, submit criteria verification, incomplete items check and display
###* 2. Dynamically generates any UI specified in input datasheet-allows for any number of options, specific to different widgets
###* 3. Dynamic tabPanels generated by grouping variable, with next and previous buttons, dynamically generated, scroll to top
###* APP STRUCTURE
###* GLOBAL: libraries, top of page scroll, theme, close page check, busy indicator
###* UI
###*  sidebar: raffle submit, progress bar, submit button w/ disable option and tooltip, dynamic unanswered items on submit
###*  mainpage: uiOutput("tab_UI") defined in server, is multiple tabpanels with two column for each item, navigation buttons on bottom
###* SERVER: 
###*  1. Tab Panel- ui_func(generates html widgets) -> survey_items_rows_UI in ui_survey_module.R(calls ui_func for each tab) -> 
###*       tab_func(calls widgets and adds nav buttons) -> do.call(calls tab_func for each tab, can also add individual modules)
###*  2. Gather inputs- From read_data.R that builds UI content, generates ids, create reactiveValues to strore data
###*  3. Progress bar- include what is essential to complete, optional enable/disable submit based on criteria, display unanswered items
###*  4. Submit responses- show unanswered items and modal to confirm submit
###*  5. Save to googlesheet- data from responses and optional email data
###*  6. Previous and next buttons- dynamically generates buttons at bottom of page to navigate between adjacent pages
###*  OUTPUT: This will generate a survey with two-column layout, for each app, just need to customize: 
###*    1. survey_items_dat- create xlsx file with ui data, optional grouping factor for tabs, 
###*    2. Title of app and intro- in titlePanel in UI and intro h5 in ui_survey_module.R
###*    3. Shortened names for tab heads in unanswered_items func and tab_func 
###*    4. Googlesheet-create sheet for storing item responses and email dat, create column headers as described in save to googlesheet 
###*      section in server.R, save url, after opening to share in "keys/googlesheet_url_information.R" 

# Set-up ------------------------------------------------------------------

###*** Libraries
library(shiny)
library(shinyWidgets) # Progressbar Uncomment for multi-select widget
library(tidyverse)
library(googledrive)
library(googlesheets4)
library(shinythemes)
library(shinyjs)
# Adds js function to scroll to top of page on navigation
jscode <- "shinyjs.toTop = function() {window.scrollTo(0, 0);}"

###*** Read data in from R/read_data.R
## Private googlesheet url DO NOT PUBLISH Keys FOLDER
source("keys/googlesheet_url_information.R")

# Define UI
fluidPage(
  theme = shinytheme("flatly"),
## For disable/able buttons
shinyjs::useShinyjs(), # For disable/able buttons, top scroll
extendShinyjs(text = jscode, functions = "toTop"), # Adds js function to scroll to top of page on navigation
# Add check to navigate from app
tags$head(tags$script(HTML("
          // Enable navigation prompt
          window.onbeforeunload = function() {
              return 'Leave site? Changes may not be saved.';
          };
      "))),
## Busy indicator
  shinysky::busyIndicator(text = "Processing ... ", wait = 1000),
  tags$head(
    tags$style(HTML(".shinysky-busy-indicator {z-index: 1000;}"))
  ),

# App UI ------------------------------------------------------------------

  ## Application title
    titlePanel("NIC Hair Design Exam 2023 Survey"),

  ## Sidebar with respondent information in sidebar, and item survey in main
    sidebarLayout(
      ###*** SIDEBAR
        sidebarPanel(
        ## Optional raffle enter. If 'Yes' will save email to googlesheets email sheet
          radioButtons(
            inputId = "enter_raffle",
            label = "Enter raffle?",
            choices = c("Yes", "No")
          ),
          textInput(
            inputId = "email_address",
            label = "Enter email address for raffle"
          ),
        ## Progress bar to track completion of survey items
          progressBar(
            id = "completion_progress", value = 0, 
            status = "info", display_pct = TRUE, striped = TRUE, title = "Completion"),
        ## actionButton for submitting item responses, starts disabled until items complete, popover for information on enabling
          tags$div(style="display:inline-block",title="Button clickable upon completion of all items",
            shinyjs::disabled(
              actionButton(
              inputId = "submit",
              label = "Submit Answers"
              )
            )
          ),
        ## Renders table containing unanswered items, if present, will disappear if none
          uiOutput("unanswered_df")
        ),

      ###*** MAIN
      ## Main Panel contains survey items
        mainPanel(
            uiOutput("tab_UI")
        )
    ) # Closing sidebarLayout paren
) # Closing fluidPage paren
